version: '3'

volumes:
  commurz-postgres:

services:
  postgres:
    image: postgres:15.3-alpine3.18
    volumes:
      - commurz-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    container_name: commurz-postgres
    ports:
      - 5432:5432
  
  redis:
    image: redis:7.0-alpine3.18
    ports:
      - 6379:6379
    container_name: commurz-redis

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_HOSTNAME: mailhog.example
    container_name: commurz-mailhog