// @generated by protoc-gen-connect-es v0.13.1 with parameter "target=ts"
// @generated from file commurz/v1/commurz.proto (package commurz.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddProductToCartRequest, Cart, CheckoutAllRequest, CreateProductRequest, Empty, FindByIDRequest, ListAppProductsRequest, ListAppProductsResponse, ListBackofficeProductsRequest, ListBackofficeProductsResponse, ListUsersRequest, ListUsersResponse, Product, UpdateProductStockRequest, User } from "./commurz_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition
 *
 * @generated from service commurz.v1.CommurzService
 */
export const CommurzService = {
  typeName: "commurz.v1.CommurzService",
  methods: {
    /**
     * user
     *
     * @generated from rpc commurz.v1.CommurzService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.FindUserByID
     */
    findUserByID: {
      name: "FindUserByID",
      I: FindByIDRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.FindUserByToken
     */
    findUserByToken: {
      name: "FindUserByToken",
      I: Empty,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * storefront query
     *
     * @generated from rpc commurz.v1.CommurzService.ListAppProducts
     */
    listAppProducts: {
      name: "ListAppProducts",
      I: ListAppProductsRequest,
      O: ListAppProductsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * order & inventory query
     *
     * @generated from rpc commurz.v1.CommurzService.FindCartByUserToken
     */
    findCartByUserToken: {
      name: "FindCartByUserToken",
      I: Empty,
      O: Cart,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.FindProductByID
     */
    findProductByID: {
      name: "FindProductByID",
      I: FindByIDRequest,
      O: Product,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.ListBackofficeProducts
     */
    listBackofficeProducts: {
      name: "ListBackofficeProducts",
      I: ListBackofficeProductsRequest,
      O: ListBackofficeProductsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * order & inventory command
     *
     * @generated from rpc commurz.v1.CommurzService.CreateProduct
     */
    createProduct: {
      name: "CreateProduct",
      I: CreateProductRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.UpdateProductStock
     */
    updateProductStock: {
      name: "UpdateProductStock",
      I: UpdateProductStockRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.AddProductToCart
     */
    addProductToCart: {
      name: "AddProductToCart",
      I: AddProductToCartRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.CheckoutAll
     */
    checkoutAll: {
      name: "CheckoutAll",
      I: CheckoutAllRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

