// @generated by protoc-gen-connect-es v0.13.1 with parameter "target=ts"
// @generated from file commurz/v1/commurz.proto (package commurz.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddProductToCartRequest, Cart, ChangeProductStockRequest, CheckoutAllRequest, CreateProductRequest, FindByIDRequest, ListBackofficeProductsRequest, ListBackofficeProductsResponse, ListUsersRequest, ListUsersResponse, Order, Product, User } from "./commurz_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Service definition
 *
 * @generated from service commurz.v1.CommurzService
 */
export const CommurzService = {
  typeName: "commurz.v1.CommurzService",
  methods: {
    /**
     * user
     *
     * @generated from rpc commurz.v1.CommurzService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.FindUserByID
     */
    findUserByID: {
      name: "FindUserByID",
      I: FindByIDRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * backoffice
     *
     * @generated from rpc commurz.v1.CommurzService.ListBackofficeProducts
     */
    listBackofficeProducts: {
      name: "ListBackofficeProducts",
      I: ListBackofficeProductsRequest,
      O: ListBackofficeProductsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * product
     *
     * @generated from rpc commurz.v1.CommurzService.CreateProduct
     */
    createProduct: {
      name: "CreateProduct",
      I: CreateProductRequest,
      O: Product,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.AddProductStock
     */
    addProductStock: {
      name: "AddProductStock",
      I: ChangeProductStockRequest,
      O: Product,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.ReduceProductStock
     */
    reduceProductStock: {
      name: "ReduceProductStock",
      I: ChangeProductStockRequest,
      O: Product,
      kind: MethodKind.Unary,
    },
    /**
     * cart
     *
     * @generated from rpc commurz.v1.CommurzService.AddProductToCart
     */
    addProductToCart: {
      name: "AddProductToCart",
      I: AddProductToCartRequest,
      O: Cart,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc commurz.v1.CommurzService.CheckoutAll
     */
    checkoutAll: {
      name: "CheckoutAll",
      I: CheckoutAllRequest,
      O: Order,
      kind: MethodKind.Unary,
    },
  }
} as const;

